/*
 * This source file was generated by the Gradle 'init' task
 */
package org.oejava.example;

import org.oejava.oe.ExampleEnclave;

public class App {

  // test greeting method
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    long h = ExampleEnclave.create("../build/artifacts/enclaves/example/example.signed", true);
    if (h == 0)
      throw new RuntimeException("Failed to create enclave");
    try {
      int rc = ExampleEnclave.helloworld(h);
      if (rc != 0)
        throw new RuntimeException("ECALL failed rc=" + rc);
    } finally { ExampleEnclave.destroy(h); }
  }
}
