// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <cstdio>

#include "example_t.h" // trusted "example" header file - generated by oeedger8r
#include "openenclave/bits/result.h"
#include <openenclave/tracee.h>

using namespace std;

// ECALL implementation
void ecall_helloworld() {
  fprintf(stdout, "[ENCLAVE] Hello world from the enclave\n");

  // Callback into the host using its ocall
  oe_result_t result = ocall_helloworld();
  if (result != OE_OK) {
    fprintf(stderr,
            "[ENCLAVE] Call to host_helloworld failed: result=%d (%s)\n",
            result, oe_result_str(result));
  }
}
